language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python travis_test_tool.py -v Giscle_api/video_data.mp4 